repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      # - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.60.3
    hooks:
      - id: golangci-lint
        args: ["--fast"]
